description = "Wolfi FIPS Java Builder"

[stack]
  id = "taha/wolfi-build-image"
  build-image = "ghcr.io/taha2samy/java_fck_fips_builder:latest"
  run-image = "ghcr.io/taha2samy/java_fck_fips_running:latest"

[lifecycle]
  version = "0.19.0"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"

[[buildpacks]]
  uri = "docker://ghcr.io/taha2samy/fips-java:1.0.1"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/ca-certificates:3.12.3"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/syft:2.33.1"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/gradle:8.5.2"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/maven:6.22.8"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/sbt:6.22.10"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/executable-jar:6.15.3"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/spring-boot:5.36.3"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/apache-tomcat:8.9.8"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/dist-zip:5.12.3"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/procfile:5.13.3"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/jattach:1.12.3"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/azure-application-insights:6.2.4"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/google-stackdriver:10.2.3"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/datadog:6.10.1"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java-memory-assistant:1.10.3"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/environment-variables:4.11.3"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/image-labels:4.12.3"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
  [[order.group]]
    id = "taha/fips-java"
  [[order.group]]
    id = "paketo-buildpacks/syft"
    optional = true
  [[order.group]]
    id = "paketo-buildpacks/maven"
  [[order.group]]
    id = "paketo-buildpacks/executable-jar"
    optional = true
  [[order.group]]
    id = "paketo-buildpacks/spring-boot"
    optional = true

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
  [[order.group]]
    id = "taha/fips-java"
  [[order.group]]
    id = "paketo-buildpacks/syft"
    optional = true
  [[order.group]]
    id = "paketo-buildpacks/gradle"
  [[order.group]]
    id = "paketo-buildpacks/executable-jar"
    optional = true
  [[order.group]]
    id = "paketo-buildpacks/spring-boot"
    optional = true

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
  [[order.group]]
    id = "taha/fips-java"
  [[order.group]]
    id = "paketo-buildpacks/syft"
    optional = true
  [[order.group]]
    id = "paketo-buildpacks/sbt"
  [[order.group]]
    id = "paketo-buildpacks/executable-jar"
    optional = true

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
  [[order.group]]
    id = "taha/fips-java"
  [[order.group]]
    id = "paketo-buildpacks/executable-jar"
