description = "Wolfi FIPS Java Builder"

[stack]
  id = "io.fckfips.stacks.wolfi"
  build-image = "ghcr.io/taha2samy/java-build-base:latest"
  run-image = "ghcr.io/taha2samy/java-run-base:latest"

[lifecycle]
  version = "0.19.0"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"

[[buildpacks]]
  uri = "docker://ghcr.io/taha2samy/java-fips-meta:1.0.0"

[[order]]
  [[order.group]]
    id = "fckfips/java"
    version = "1.0.0"
