name: Buildpack Pipeline

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: localhost:5001

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - name: Start local registry
        run: |
          docker run -d -p 5001:5001 --name registry registry:2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver-opts: network=host

      - name: Install Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.12.3

      - name: Prepare Builder Config for Local Registry
        run: |
          sed -i 's|ghcr.io/taha2samy|localhost:5001|g' ./2-builder/builder.toml

      # - id: build-base
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./build-image
      #     file: ./build-image/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ env.REGISTRY }}/java_fck_fips_builder:latest

      # - id: run-base
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./run-image
      #     file: ./run-image/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ env.REGISTRY }}/java_fck_fips_running:latest

      - name: Package Buildpack
        run: |
          pack buildpack package ${{ env.REGISTRY }}/fips-java:1.0.1 \
            --path ./fips-java-shim \
            --format image \
            --target linux/amd64 \
            --target linux/arm64 \
            --publish

      - name: Create Builder
        run: |
          pack builder create ${{ env.REGISTRY }}/java-fips-builder:latest \
            --config ./2-builder/builder.toml \
            --target linux/amd64 \
            --target linux/arm64 \
            --publish
